language: csharp
solution: CompuMaster.Calendar.VS2012.sln

before_install:
  - nuget install NUnit.Runners -Version 3.12.0 -OutputDirectory testrunner

install:
  - nuget restore CompuMaster.Calendar.VS2012.sln

script:
  - msbuild /p:Configuration=Release /p:Platform="Any CPU" /p:PostBuildEvent="" CompuMaster.Calendar.VS2012.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.12.0/tools/nunit3-console.exe ./CompuMaster.Test.Calendar/bin/CompuMaster.Test.Calendar.dll