Imports NUnit.Framework

Namespace CompuMaster.Test.Calendar

    <TestFixture()> Public Class MonthNumberTest

        <Test> Public Sub Parse()
            Assert.AreEqual("10", CompuMaster.Calendar.MonthNumber.Parse("10").ToString)
            Assert.AreEqual("01", CompuMaster.Calendar.MonthNumber.Parse("01").ToString)
            Assert.AreEqual("10", CompuMaster.Calendar.MonthNumber.Parse("Oct", "MMM", System.Globalization.CultureInfo.GetCultureInfo("en-US")).ToString)
            Assert.AreEqual("01", CompuMaster.Calendar.MonthNumber.Parse("Jan", "MMM", System.Globalization.CultureInfo.GetCultureInfo("en-US")).ToString)
            Assert.AreEqual("12", CompuMaster.Calendar.MonthNumber.Parse("Dec", "MMM", System.Globalization.CultureInfo.GetCultureInfo("en-US")).ToString)
            Assert.Throws(Of ArgumentNullException)(Sub()
                                                        CompuMaster.Calendar.MonthNumber.Parse(Nothing, "MMM", System.Globalization.CultureInfo.GetCultureInfo("en-US"))
                                                    End Sub)
            Assert.Throws(Of ArgumentNullException)(Sub()
                                                        CompuMaster.Calendar.MonthNumber.Parse("", "MMM", System.Globalization.CultureInfo.GetCultureInfo("en-US"))
                                                    End Sub)
            Assert.Throws(Of ArgumentException)(Sub()
                                                    CompuMaster.Calendar.MonthNumber.Parse("invalid-value", "MMM", System.Globalization.CultureInfo.GetCultureInfo("en-US"))
                                                End Sub)
            Assert.AreEqual("01", CompuMaster.Calendar.MonthNumber.Parse("01", "MM", System.Globalization.CultureInfo.GetCultureInfo("en-US")).ToString)
            Assert.AreEqual("10", CompuMaster.Calendar.MonthNumber.Parse("10", "MM", System.Globalization.CultureInfo.GetCultureInfo("en-US")).ToString)
            Assert.AreEqual("01", CompuMaster.Calendar.MonthNumber.Parse("1", "M", System.Globalization.CultureInfo.GetCultureInfo("en-US")).ToString)
            Assert.AreEqual("01", CompuMaster.Calendar.MonthNumber.Parse("01", "M", System.Globalization.CultureInfo.GetCultureInfo("en-US")).ToString)
            Assert.AreEqual("10", CompuMaster.Calendar.MonthNumber.Parse("10", "MM", System.Globalization.CultureInfo.GetCultureInfo("en-US")).ToString)
            Assert.AreEqual("12", CompuMaster.Calendar.MonthNumber.Parse("12", "MM", System.Globalization.CultureInfo.GetCultureInfo("en-US")).ToString)
            Assert.AreEqual("04", CompuMaster.Calendar.MonthNumber.Parse("04", "MM", System.Globalization.CultureInfo.GetCultureInfo("en-US")).ToString)
        End Sub

        <Test> Public Sub TryParse()
            Dim Buffer As CompuMaster.Calendar.MonthNumber = Nothing
            Assert.AreEqual(True, CompuMaster.Calendar.MonthNumber.TryParse("Oct", "MMM", System.Globalization.CultureInfo.GetCultureInfo("en-US"), Buffer), "#010")
            Assert.AreEqual("10", Buffer.ToString, "#020")
            Assert.AreEqual(True, CompuMaster.Calendar.MonthNumber.TryParse("Jan", "MMM", System.Globalization.CultureInfo.GetCultureInfo("en-US"), Buffer), "#011")
            Assert.AreEqual("01", Buffer.ToString, "#021")
            Assert.AreEqual(True, CompuMaster.Calendar.MonthNumber.TryParse("Dec", "MMM", System.Globalization.CultureInfo.GetCultureInfo("en-US"), Buffer), "#012")
            Assert.AreEqual("12", Buffer.ToString, "#022")
            Dim ExpectedMarchShortNameOnCurrentPlatform As String = New DateTime(2020, 3, 1).ToString("MMM", System.Globalization.CultureInfo.GetCultureInfo("de-DE")) 'Linux systems/Mono: "Mär", Windows systems: "Mrz"
            System.Console.WriteLine("SPECIAL CASE HANDLING: month March in German culture appears differently between windows and linux/mono systems")
            System.Console.WriteLine("SPECIAL CASE HANDLING: month March in German culture expected as """ & ExpectedMarchShortNameOnCurrentPlatform & """")
            Assert.AreEqual(True, CompuMaster.Calendar.MonthNumber.TryParse(ExpectedMarchShortNameOnCurrentPlatform, "MMM", System.Globalization.CultureInfo.GetCultureInfo("de-DE"), Buffer), "#013")
            Assert.AreEqual("03", Buffer.ToString, "#023")
            Assert.AreEqual(True, CompuMaster.Calendar.MonthNumber.TryParse("Okt", "MMM", System.Globalization.CultureInfo.GetCultureInfo("de-DE"), Buffer), "#014")
            Assert.AreEqual("10", Buffer.ToString, "#024")
            Assert.AreEqual(True, CompuMaster.Calendar.MonthNumber.TryParse("Jan", "MMM", System.Globalization.CultureInfo.GetCultureInfo("de-DE"), Buffer), "#015")
            Assert.AreEqual("01", Buffer.ToString, "#025")
            Assert.AreEqual(True, CompuMaster.Calendar.MonthNumber.TryParse("Dez", "MMM", System.Globalization.CultureInfo.GetCultureInfo("de-DE"), Buffer), "#016")
            Assert.AreEqual("12", Buffer.ToString, "#026")
            Buffer = Nothing
            Assert.AreEqual(False, CompuMaster.Calendar.MonthNumber.TryParse(Nothing, "MMM", System.Globalization.CultureInfo.GetCultureInfo("en-US"), Buffer), "#030")
            Assert.AreEqual(Nothing, Buffer, "#050")
            Assert.AreEqual(False, CompuMaster.Calendar.MonthNumber.TryParse("", "MMM", System.Globalization.CultureInfo.GetCultureInfo("en-US"), Buffer), "#031")
            Assert.AreEqual(Nothing, Buffer, "#051")
            Assert.AreEqual(False, CompuMaster.Calendar.MonthNumber.TryParse("invalid-value", "MMM", System.Globalization.CultureInfo.GetCultureInfo("en-US"), Buffer), "#032")
            Assert.AreEqual(Nothing, Buffer, "#052")
            Assert.AreEqual(True, CompuMaster.Calendar.MonthNumber.TryParse("January", "MMMM", System.Globalization.CultureInfo.GetCultureInfo("en-US"), Buffer), "#033")
            Assert.AreEqual("01", Buffer.ToString, "#053")
            Assert.AreEqual(True, CompuMaster.Calendar.MonthNumber.TryParse("October", "MMMM", System.Globalization.CultureInfo.GetCultureInfo("en-US"), Buffer), "#034")
            Assert.AreEqual("10", Buffer.ToString, "#054")
            Assert.AreEqual(True, CompuMaster.Calendar.MonthNumber.TryParse("January", "MMMM", System.Globalization.CultureInfo.GetCultureInfo("en-US"), Buffer), "#035")
            Assert.AreEqual("01", Buffer.ToString, "#055")
            Assert.AreEqual(True, CompuMaster.Calendar.MonthNumber.TryParse("October", "MMMM", System.Globalization.CultureInfo.GetCultureInfo("en-US"), Buffer), "#036")
            Assert.AreEqual("10", Buffer.ToString, "#056")
            Assert.AreEqual(True, CompuMaster.Calendar.MonthNumber.TryParse("01", "MM", System.Globalization.CultureInfo.GetCultureInfo("en-US"), Buffer), "#037")
            Assert.AreEqual("01", Buffer.ToString, "#057")
            Assert.AreEqual(True, CompuMaster.Calendar.MonthNumber.TryParse("10", "MM", System.Globalization.CultureInfo.GetCultureInfo("en-US"), Buffer), "#038")
            Assert.AreEqual("10", Buffer.ToString, "#058")
            Assert.AreEqual(True, CompuMaster.Calendar.MonthNumber.TryParse("1", "M", System.Globalization.CultureInfo.GetCultureInfo("en-US"), Buffer), "#039")
            Assert.AreEqual("01", Buffer.ToString, "#059")
            Assert.AreEqual(True, CompuMaster.Calendar.MonthNumber.TryParse("10", "M", System.Globalization.CultureInfo.GetCultureInfo("en-US"), Buffer), "#040")
            Assert.AreEqual("10", Buffer.ToString, "#060")
        End Sub

        <Test> Public Sub Conversions()
            Assert.AreEqual("10", CType(New CompuMaster.Calendar.MonthNumber(10), String))
            Assert.AreEqual(Nothing, CType(CType(Nothing, CompuMaster.Calendar.MonthNumber), String))
            Assert.AreEqual(Nothing, CType(CType(Nothing, String), CompuMaster.Calendar.MonthNumber))
            Assert.AreEqual(Nothing, CType(String.Empty, CompuMaster.Calendar.MonthNumber))
            Assert.AreEqual("10", CType("10", CompuMaster.Calendar.MonthNumber).ToString)
        End Sub

        <Test> Public Sub ParseFromUniqueShortName()
            Assert.AreEqual("10", CompuMaster.Calendar.MonthNumber.ParseFromUniqueShortName("Oct").ToString)
            Assert.AreEqual("01", CompuMaster.Calendar.MonthNumber.ParseFromUniqueShortName("Jan").ToString)
            Assert.AreEqual("12", CompuMaster.Calendar.MonthNumber.ParseFromUniqueShortName("Dec").ToString)
        End Sub

        <Test> Public Sub UniqueShortName()
            Assert.AreEqual("Oct", (New CompuMaster.Calendar.MonthNumber("10")).UniqueShortName)
            Assert.AreEqual("Jan", (New CompuMaster.Calendar.MonthNumber("01")).UniqueShortName)
            Assert.AreEqual("Dec", (New CompuMaster.Calendar.MonthNumber("12")).UniqueShortName)
        End Sub

        <Test()> Public Sub Compares()
            Dim value1 As New CompuMaster.Calendar.MonthNumber(1)
            Dim value2 As New CompuMaster.Calendar.MonthNumber(12)
            Dim value3 As New CompuMaster.Calendar.MonthNumber(1)
            Assert.AreEqual(False, value1 > value2)
            Assert.AreEqual(True, value1 < value2)
            Assert.AreEqual(False, value1 >= value2)
            Assert.AreEqual(True, value1 <= value2)
            Assert.AreEqual(True, value1 >= value3)
            Assert.AreEqual(True, value1 <= value3)
            Assert.AreEqual(True, value1 = value3)
            Assert.AreEqual(value1, value3)
            Assert.AreEqual(False, value1 <> value3)
            Assert.AreEqual(False, value1 > value3)
            Assert.AreEqual(False, value1 < value3)
            Assert.AreNotEqual(Nothing, value3)
            Assert.AreNotEqual(value3, Nothing)
            Assert.AreNotEqual(DBNull.Value, value3)
            Assert.AreNotEqual(value3, DBNull.Value)
            Assert.AreNotEqual(New System.Text.StringBuilder, value3)
            Assert.AreNotEqual(value3, New System.Text.StringBuilder)
            Assert.AreNotEqual(String.Empty, value3)
            Assert.AreNotEqual(value3, String.Empty)
            Assert.AreNotEqual(5, value3)
            Assert.AreNotEqual(value3, 5)
            value1 = Nothing
            value2 = Nothing
            Assert.AreEqual(True, value1 = value2)
            Assert.AreEqual(False, value1 <> value2)
            Assert.AreEqual(False, value1 < value2)
            Assert.AreEqual(False, value1 > value2)
            Assert.AreEqual(True, value1 <= value2)
            Assert.AreEqual(True, value1 >= value2)
            Assert.AreEqual(False, value1 = value3)
            Assert.AreEqual(True, value1 <> value3)
            Assert.AreEqual(True, value1 < value3)
            Assert.AreEqual(False, value1 > value3)
            Assert.AreEqual(True, value1 <= value3)
            Assert.AreEqual(False, value1 >= value3)
            Assert.AreEqual(False, value3 = value2)
            Assert.AreEqual(True, value3 <> value2)
            Assert.AreEqual(False, value3 < value2)
            Assert.AreEqual(True, value3 > value2)
            Assert.AreEqual(False, value3 <= value2)
            Assert.AreEqual(True, value3 >= value2)
        End Sub

        <Test()> Public Sub MonthNames()
            Dim value1 As New CompuMaster.Calendar.MonthNumber(1)
            Dim value2 As New CompuMaster.Calendar.MonthNumber(12)
            Assert.AreEqual("Jan", value1.UniqueShortName)
            Assert.AreEqual("Dec", value2.UniqueShortName)
            Assert.AreEqual("Jan", value1.MonthShortName(System.Globalization.CultureInfo.GetCultureInfo("en-US")))
            Assert.AreEqual("Dec", value2.MonthShortName(System.Globalization.CultureInfo.GetCultureInfo("en-US")))
            Assert.AreEqual("Jan", value1.MonthShortName(System.Globalization.CultureInfo.GetCultureInfo("de-DE")))
            Assert.AreEqual("Dez", value2.MonthShortName(System.Globalization.CultureInfo.GetCultureInfo("de-DE")))
            Assert.AreEqual("January", value1.MonthName(System.Globalization.CultureInfo.GetCultureInfo("en-US")))
            Assert.AreEqual("December", value2.MonthName(System.Globalization.CultureInfo.GetCultureInfo("en-US")))
            Assert.AreEqual("Januar", value1.MonthName(System.Globalization.CultureInfo.GetCultureInfo("de-DE")))
            Assert.AreEqual("Dezember", value2.MonthName(System.Globalization.CultureInfo.GetCultureInfo("de-DE")))
            Assert.AreEqual("Jan", value1.MonthShortName("en-US"))
            Assert.AreEqual("Dec", value2.MonthShortName("en-US"))
            Assert.AreEqual("January", value1.MonthName("en-US"))
            Assert.AreEqual("December", value2.MonthName("en-US"))
        End Sub

        <Test> Public Sub Add()
            Dim value1 As New CompuMaster.Calendar.MonthNumber(1)
            Dim value2 As New CompuMaster.Calendar.MonthNumber(12)
            Dim value6 As New CompuMaster.Calendar.MonthNumber(5)
            Assert.AreEqual(value6, value1.AddMonths(4))
            Assert.Catch(Of NotSupportedException)(Sub()
                                                       Assert.AreEqual(value6, value1.AddMonths(-8))
                                                   End Sub)
            Assert.AreEqual(New CompuMaster.Calendar.MonthNumber(12), value1.AddMonths(11))
            Assert.AreEqual(New CompuMaster.Calendar.MonthNumber(2), value2.AddMonths(-10))
        End Sub

        <Test> Public Sub SmallerBiggerEquals()
            Assert.Multiple(Sub()
                                Assert.IsTrue(New CompuMaster.Calendar.MonthNumber(9) = New CompuMaster.Calendar.MonthNumber(9))
                                Assert.IsTrue(New CompuMaster.Calendar.MonthNumber(1) <> New CompuMaster.Calendar.MonthNumber(9))
                                Assert.IsTrue(New CompuMaster.Calendar.MonthNumber(1) < New CompuMaster.Calendar.MonthNumber(9))
                                Assert.IsTrue(New CompuMaster.Calendar.MonthNumber(9) > New CompuMaster.Calendar.MonthNumber(1))
                                Assert.IsFalse(New CompuMaster.Calendar.MonthNumber(9) <> New CompuMaster.Calendar.MonthNumber(9))
                                Assert.IsFalse(New CompuMaster.Calendar.MonthNumber(1) = New CompuMaster.Calendar.MonthNumber(9))
                                Assert.IsFalse(New CompuMaster.Calendar.MonthNumber(1) > New CompuMaster.Calendar.MonthNumber(9))
                                Assert.IsFalse(New CompuMaster.Calendar.MonthNumber(9) < New CompuMaster.Calendar.MonthNumber(1))

                                Assert.AreEqual(New CompuMaster.Calendar.MonthNumber(9), New CompuMaster.Calendar.MonthNumber(9))
                                Assert.AreNotEqual(New CompuMaster.Calendar.MonthNumber(1), New CompuMaster.Calendar.MonthNumber(9))
                                Assert.Less(New CompuMaster.Calendar.MonthNumber(1), New CompuMaster.Calendar.MonthNumber(9))
                                Assert.Greater(New CompuMaster.Calendar.MonthNumber(9), New CompuMaster.Calendar.MonthNumber(1))
                                Assert.That(New CompuMaster.Calendar.MonthNumber(1), NUnit.Framework.Is.LessThan(New CompuMaster.Calendar.MonthNumber(9)))
                                Assert.That(New CompuMaster.Calendar.MonthNumber(9), NUnit.Framework.Is.GreaterThan(New CompuMaster.Calendar.MonthNumber(1)))
                            End Sub)
        End Sub

        <Test> Public Sub Sorting()
            Dim Values As New Generic.List(Of CompuMaster.Calendar.MonthNumber)
            Values.Add(New CompuMaster.Calendar.MonthNumber(11))
            Values.Add(New CompuMaster.Calendar.MonthNumber(10))
            Values.Add(New CompuMaster.Calendar.MonthNumber)
            Values.Add(New CompuMaster.Calendar.MonthNumber(9))

            Values.Sort()

            Assert.AreEqual(New CompuMaster.Calendar.MonthNumber, Values(0))
            Assert.AreEqual(New CompuMaster.Calendar.MonthNumber(9), Values(1))
            Assert.AreEqual(New CompuMaster.Calendar.MonthNumber(10), Values(2))
            Assert.AreEqual(New CompuMaster.Calendar.MonthNumber(11), Values(3))
        End Sub

    End Class

End Namespace